name:    repo-alarm
version: 0.1.0.0
license: AGPL

dependencies:
  - base >= 4.7 && < 5
  - text
  - aeson
  - yesod
  - bytestring
  - process
  - http-conduit
  - random

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

executables:
  repo-alarm:
    source-dirs:      src
    main:             Main.hs
